version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
  # Broken; see: https://github.com/dependabot/dependabot-core/issues/11946
  # - package-ecosystem: "uv"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   cooldown:
  #     default-days: 7
  #   groups:
  #     uv:
  #       patterns:
  #         - "*"
