name: pyx-auth-action
description: Authenticate to pyx using Trusted Publishing

branding:
  icon: lock
  color: purple

inputs:
  workspace:
    description: |
      The pyx workspace being published to.

      Example: acme
    required: false
  registry:
    description: |
      The pyx registry being published to.

      Example: main
    required: false
  url:
    description: |
      The upload URL.

      Example: https://api.pyx.dev/v1/upload/acme/main
    required: false

outputs:
  token:
    description: "The temporary upload token"
    value: ${{ steps.exchange.outputs.token }}
  url:
    description: "The upload URL"
    value: ${{ steps.exchange.outputs.url }}

runs:
  using: composite
  steps:
    - name: setup uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0

    - name: exchange
      id: exchange
      run: |
        uv run --script "${GITHUB_ACTION_PATH}/action.py"
      shell: bash
      env:
        GHA_PYX_INPUT_WORKSPACE: ${{ inputs.workspace }}
        GHA_PYX_INPUT_REGISTRY: ${{ inputs.registry }}
        GHA_PYX_INPUT_URL: ${{ inputs.url }}
        # Not part of the public interface, but allows overriding the API base for testing.
        GHA_PYX_INPUT_INTERNAL_API_BASE: ${{ env.GHA_PYX_INPUT_INTERNAL_API_BASE || 'https://api.pyx.dev' }}
