name: pyx-auth-action
description: Authenticate to pyx using Trusted Publishing

branding:
  icon: lock
  color: purple

inputs:
  url:
    description: "Your registry's upload URL"
    required: true

outputs:
  token:
    description: "The temporary upload token"
    value: ${{ steps.exchange.outputs.token }}

runs:
  using: composite
  steps:
    - name: setup uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0

    - name: exchange
      id: exchange
      run: |
        uv run --script "${GITHUB_ACTION_PATH}/action.py"
      shell: bash
      env:
        GHA_PYX_INPUT_URL: ${{ inputs.url }}
