name: pyx-auth-action
description: Authenticate to pyx using Trusted Publishing

branding:
  icon: lock
  color: purple

inputs:
  index:
    description: |
      The name of the pyx index (in your `pyproject.toml`) to authenticate against.

      To use this setting, you must have an appropriate `[[tool.uv.index]]`
      section in your `pyproject.toml`.

      See: https://docs.astral.sh/uv/guides/package/#publishing-your-package
  workspace:
    description: |
      The pyx workspace being published to.

      Example: acme
    required: false
  registry:
    description: |
      The pyx registry being published to.

      Example: main
    required: false
  url:
    description: |
      The upload URL.

      Example: https://api.pyx.dev/v1/upload/acme/main
    required: false

outputs:
  token:
    description: "The temporary upload token"
    value: ${{ steps.exchange.outputs.token }}
  url:
    description: "The upload URL"
    value: ${{ steps.exchange.outputs.url }}

runs:
  using: composite
  steps:
    - name: fetch temporary uv
      uses: dawidd6/action-download-artifact@v11
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repo: astral-sh/uv
        workflow: ci.yml
        pr: 16234
        name: "uv-linux-libc-.+"
        name_is_regexp: true

    - name: Add uv to PATH
      shell: bash
      run: |
        path=$(find "$(pwd)" -name 'uv-linux-libc*' | head -n 1)
        echo "${path}" >> ${GITHUB_PATH}

    - name: exchange
      id: exchange
      run: |
        uv run --script "${GITHUB_ACTION_PATH}/action.py"
      shell: bash
      env:
        GHA_PYX_INPUT_INDEX: ${{ inputs.index }}
        GHA_PYX_INPUT_WORKSPACE: ${{ inputs.workspace }}
        GHA_PYX_INPUT_REGISTRY: ${{ inputs.registry }}
        GHA_PYX_INPUT_URL: ${{ inputs.url }}
        # Not part of the public interface, but allows overriding the API base for testing.
        GHA_PYX_INPUT_INTERNAL_API_BASE: ${{ env.GHA_PYX_INPUT_INTERNAL_API_BASE || 'https://api.pyx.dev' }}
