name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

env:
  PYX_UPLOAD_URL: https://astral-sh-staging-api.pyx.dev/v1/upload/test/internal

jobs:
  test-exchange-only:
    if: ${{ github.event.pull_request.head.repo.full_name == 'astral-sh/pyx-auth-action' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for testing the action itself
      contents: read # for private repos

    environment: test

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: ./
        id: auth
        with:
          url: ${{ env.PYX_UPLOAD_URL }}

  test-publish-e2e:
    if: ${{ github.event.pull_request.head.repo.full_name == 'astral-sh/pyx-auth-action' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for testing the action itself
      contents: read # for private repos

    environment: test

    steps:
      - name: setup uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: ./
        id: auth
        with:
          url: ${{ env.PYX_UPLOAD_URL }}

      - name: Checkout sampleproject
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: pypa/sampleproject
          path: sampleproject
          persist-credentials: false

      - name: Prep sampleproject
        working-directory: sampleproject
        run: |
          stamp=$(date +%s)
          version="4.0.${stamp}"

          # Replace the version in pyproject.toml
          sed -i "s/^version = \".*\"/version = \"${version}\"/" pyproject.toml

      - name: Build and publish package
        run: |
          uv build
          uv publish --publish-url "${PYX_UPLOAD_URL}"
        working-directory: sampleproject
        env:
          UV_PUBLISH_TOKEN: ${{ steps.auth.outputs.token }}
